### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-graphql#25]
- Clarify that the guide is focused on creating/enabling a GraphQL endpoint/service for an application;

- Clarity that GraqhQL isn't for data alone but query language for (REST) APIs;

- Can we explain and bring in "query" and "mutation" upfront?

The title, abstract, intro and section headers should be updated accordingly as we look at the above.

It will be nice if we can show starting with an existing REST application and exposing what you have there through GraphQL.  Then, MP GraphQL may have plan to do this in an easier manner down the road.  We can follow up first.

**Comment by yeekangc** [comment]
@AustinSeto @gkwan-ibm

**Comment by AustinSeto** [comment]
I followed up with Andy McCright and got the suggestion for the guide to start with an existing REST application and then add on a GraphQL endpoint as an alternate method to access the data. The same system properties will be able to be viewed through either a regular REST endpoint like `localhost:9080/system/properties` and through a request to a GraphQL endpoint. 

I think this could clarify that GraphQL is a query language and that the guide is focused on enabling GraphQL as a query language to access the data, and is focused on that endpoint rather than the data.

**Comment by yeekangc** [comment]
Closing as the latest draft addressed these questions/concerns.  Cc @priyyanshi @gkwan-ibm
