### ISSUE TITLE
ID Review

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/guide-microprofile-graphql#44]
Review for basic ID concerns (grammar, style etc) as well as overall cohesiveness and clarity of content.

**Comment by ramkumar-k-9286** [comment]
Hi 

Please find below review comments related to grammar, style etc.
The actual content as well as the rephrased content have been added. 
These have been placed under the individual sections as in the guide.
 
### OL Guide Review comments:

### What you'll learn

**Paragraph 2 -** GraphQL will only calculate these properties if they’re requested.

**Rephrase -** GraphQL calculates these properties only if they are requested. 


**Paragraph 3 -** A GraphQL service can also be used to obtain data from multiple sources such as APIs, databases, or other services. (**OR** sounds like you need to pick from any one of the sources)

**Rephrase -** A GraphQL service can also be used to obtain data from multiple sources such as APIs, databases, and other services. 


**Paragraph 3 -** It can then collate this data into a single object for the user. This simplifies data retrieval as the user only makes a single request to the GraphQL service, instead of multiple requests to the individual data sources.

**Rephrase -** It can then collate this data into a single object for the user, simplifying the data retrieval. The user makes only a single request to the GraphQL service, instead of multiple requests to the individual data sources.


**Paragraph 4 -** The GraphQL schema describes all the data types used in the GraphQL service.

**Rephrase -** The GraphQL schema describes all the data types that are used in the GraphQL service.


**Paragraph 6 -** You’ll create a GraphQL application that retrieves data from multiple `system` services. Users will make requests to the GraphQL service, which will then make requests to the `system` services. The GraphQL service will return a single JSON object containing all the system information from the `system` services.

**Rephrase -** You'll create a GraphQL application that retrieves data from multiple `system` services. Users make requests to the GraphQL service, which then makes requests to the `system` services. The GraphQL service returns a single JSON object containing all the system information from the `system` services.


**Paragraph 7 -** You’ll enable the interactive GraphQL tool called [GraphiQL](https://github.com/graphql/graphiql/tree/main/packages/graphiql) in the Open Liberty server. 

**Rephrase -** You'll enable the interactive [GraphiQL](https://github.com/graphql/graphiql/tree/main/packages/graphiql) tool in the Open Liberty server. 


### Getting started

**Paragraph 1 -** The fastest way to work through this guide is to clone the [Git repository](https://github.com/openliberty/guide-microprofile-graphql.git) and use the projects that are provided inside:

**Issue -** Link not working ( Possible that I do not have access to this specific Git repository).

 
**Paragraph 1 -** Before you begin, make sure you have all the necessary prerequisites.

**Rephrase -** Before you begin, make sure you have all the prerequisites.


### Implementing system service

**Paragraph 1 -** The `system` microservices are backend services using JAX-RS. For more details on using JAX-RS, see our [Creating a RESTful web service guide](https://www.openliberty.io/guides/rest-intro.html). This `system` microservices report system properties. Multiple instances of them will be accessed and their information will be collated by GraphQL. In a real scenario, GraphQL might access multiple different databases or other services.

**Rephrase -** The `system` microservices are backend services that use JAX-RS. For more details on using JAX-RS, see the [Creating a RESTful web service guide](https://www.openliberty.io/guides/rest-intro.html). The `system` microservices report system properties. GraphQL can access multiple instances of these `system` microservices and collate their information. In a real scenario, GraphQL might access multiple databases or other services.


**Paragraph 3 -** The `SystemMetricsResource` class provides information on the system’s resources and their usage. The `systemLoad` endpoint assembles and returns an object describing the system load. It will include the JVM heap load and processor load.

**Rephrase -** The `SystemMetricsResource` class provides information on the system resources and their usage. The `systemLoad` endpoint assembles and returns an object that describes the system load. It includes the JVM heap load and processor load.


### Implementing GraphQL resolvers

**Paragraph 9 -** Operations of the `mutation` type are be used to edit data. 

**Rephrase -** Operations of the `mutation` type are used to edit data. 


**Paragraph 10 -** Each resolver function has an `@Description` annotation, which provides a description to be used for the schema. 

**Rephrase -** Each resolver function has a `@Description` annotation, which provides a description that is used for the schema. 


### Building and running the application

**Paragraph 4 -** The `--build-arg` parameter is used to create two different `system` services. One will use Java 8, while the other will use Java 11. Run these Docker images using the provided `startContainers` script. The script will create a network for the services to communicate through. It will create the two `system` services and a GraphQL service.

**Rephrase -** The `--build-arg` parameter is used to create two different `system` services. One uses Java 8, while the other uses Java 11. Run these Docker images using the provided `startContainers` script. The script creates a network for the services to communicate through. It creates two `system` services and a GraphQL service.


### Running GraphQL queries

**Paragraph 1 -** Before making any requests, visit the [http://localhost:9082/graphql/schema.graphql]() URL. This URL returns the schema to describe the GraphQL service.

**Rephrase -** Before you make any requests, see the [http://localhost:9082/graphql/schema.graphql]() URL. This URL returns the schema that describes the GraphQL service.

**Comment by dmuelle** [comment]
## Content review
 Looks good overall, I just have a few comments
 
**Globally**:
In text descriptions treat `@` as a symbol, not a letter- ie determine whether to use "a" or "an" based on the first letter of the annotation name, not the @ symbol. For example:

 The JavaInfo class is annotated with an @Type annotation. 
-->
The JavaInfo class is annotated with a @Type annotation. 



### What you'll learn

This introduction would benefit from a concrete example- what is a common use case for Graphql? What kind of application/scenario might find it useful? Connect to some business context. Briefly- should only need a sentence or two.

### Creating GraphQL object types

I found this section difficult to understand at first. It might help to make it more clear at the outset that you are annotating Java classes that define graphQl object types. For example:

Object types define the structure of the data returned by GraphQL. Annotations that are applied to the declaration and properties of Java classes define object types. The object types are defined in their own Maven module that is included in the other modules.
--->
Object types determine the structure of the data that GraphQL returns. These object types are defined by annotations that are applied to the declaration and properties of Java classes. They are defined in their own Maven module that is included in the other modules. (_what are the other modules? Modules arent mentioned anywhere else in the guide_)

_Then, to transition from the explanation, something like:_

First, you will create the `JavaInfo`, `SystemMetrics`, and `SystemInfo` classes, all of which map to GraphQL object types. 


The explanation for the `@Name` attribute- are `vendor` and `vendorName` example values?  I had a hard time understanding the utility of this annotation or when you need it vs just mapping to an identical name. I know this comes up in more detail in the resolver section but a sentence or two to clarify might be helpful.

> The @Name annotation is used when mapping a property in a Java object to a property of a different name in the GraphQL object type. Without an @Name annotation, the Java object property is automatically mapped to a GraphQL object type property of the same name.

 If you don'ts specify a name, what is the "same name" that isn used for the GQL property? Is there a case where the GQL property already exists and you need make sure this class maps to it? When can you forego using the @Name attribute and just use the default mapping? Maybe I'm missing the point but I found this confusing.
